
language: c++
install:
      - sudo apt-get install software-properties-common && add-apt-repository ppa:george-edison55/cmake-3.x
      - sudo apt-get update -qq
      - sudo apt-get install -y -qq build-essential cmake
script:
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && make test
